### ISSUE TITLE
Evaluate coat of arms as result icons

### ISSUE THREAD

**Issue by MattSkyJumper** [crehn/DesignType#33]

**Comment by crehn** [comment]
I've started creating new coat of arms style icons. I'm not finished yet, but I think this is a good way to go. Each attribute is encoded by some emblazonment:

Simple: A hat
Powerful: A crown (somebody wearing a crown is certainly more powerful than one wearing a hat)

Abstract: A spy glass (for the guys who like seeing the whole picture)
Concrete: A sword (for those who fight the nasty details)

Pragmatic: Red (like the current icons)
Idealistic Blue

Robust: a wall (symbolizing stability)
Technologic: twelve cogs surrounding the inner shield

I tried to obey the heraldic rules roughly but I didn't succeed everywhere. Brown is normally not considered a valid tincture and there are cases where a golden crown is next to a silver shield, etc. But I think we can live with that.

Please have a look at them.

**Comment by MattSkyJumper** [comment]
hmm - just 2 cents before i will have a look:
Pragmatic is currently blue not red.
You often used the explanation " with a magnifying glass at the code" for Concrete. I know there is a difference between magnifying glass and a spy glass but both are used to see something more closely instead of zooming out...

I like the usage of sword but would use it for Simple and a mace or battle axe for powerful.
Robust and Techn.: good choice
For abstract I would use a polished silver shield for concrete a more battle ready one like an oak shield you can sse that it really has beend used (maybe some strokes on it).

**Comment by MattSkyJumper** [comment]
Oh - and if you like hats: maybe use a knight helmet for pragmatic (hit don't ask) and a bishop's cap for idealistic (religious/extremly beliefing)

**Comment by MattSkyJumper** [comment]
just had a look. The current template looks nice in general. Not that optimal are the hat, the spy glass, the colours blue and red. 
The cogs are very small, maybe some kind of fancy curved border or similar could express it.
I like the crown, the wall and the sword.

**Comment by crehn** [comment]
I'd like to have a bot more variation in there. The certificates get more interesting if the differences in the logos are more noticeable than just the symbol in the shield. I'd like to have a katana for the ninja and a fire ax for the fire fighter, etc.

In order to make the meanings clear, the type and position of the symbols/emblazonments needs to stay exactly the same.

So the difference between abstract and concrete would be that the abstract have some device for looking and the concrete have some kind of weapon. Whether the weapon is a mace, an axe, or a quarterstaff doesn't matter.

I'm still experimenting.

I don't want to use a bishop's cap as some might not like them and hesitate to print the certificate. The logos should be as positive, as cool and fancy as possible.

Nevertheless, you are right with the colors. I've mixed them up and they are anyway somewhat random and unintuitive. 

Contrary to you I quite like the hat and the spy glass. Still thinking and experimenting...

**Comment by MattSkyJumper** [comment]
Should be solved.Maybe new issue for typical hat and weapon beneath the coat of arms.
